name: build

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          version: pre-release

      - name: Install Computo extension for Quarto
        run: |
            quarto add --no-prompt computorg/computo-quarto-extension

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.8.1'
    
      - uses: julia-actions/cache@v1
        with:
          cache-registries: "true"
      
      ## Add needed packages by hand
      - name: Install Julia Dependencies
        uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1      

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
